config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :users

  get 'welcome/index'

  resources :articles do
    resources :comments
  end

  namespace :admin do
    resources :comments
  end

  namespace :api do
    resources :comments
    resources :articles
  end

  resources :comments

  root 'welcome#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: {minimum: 5}

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController

  # http_basic_authenticate_with name: "dhh", password: "lol", only: [:destroy, :index]


  def index
    # @comments = Comment.all
    @comments = Comment.paginate(:page => params[:page], :per_page => 10)

  end

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to :back
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/api/articles_controller.rb
class Api::ArticlesController < ApplicationController

  def index
    @article = Article.all

    respond_to do |format|
      format.json {render json: @article}
    end
  end
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController

  def index
    @comments = Comment.all

    respond_to do |format|
      format.json {render json: @comments}
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  # http_basic_authenticate_with name: "dhh", password: "lol", except: [:index, :show]

  def index
    @article = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    # render plain: params[:article].inspect

    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  # http_basic_authenticate_with name: "dhh", password: "lol", only: [:destroy, :index]


  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to :back
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/comments/_comment.html.erb
<p>
  <strong>Commenter: </strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment: </strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
              method: :delete,
              data: {confirm: 'Are you sure?'} %>

  <td><%= link_to 'Show', article_path(comment.article) %></td>

</p>

app/views/admin/comments/index.html.erb
<%= render 'shared/navbar' %>

<h1>Todos los Comments</h1>

<%= render @comments %>

<%= will_paginate @comments %>

<%= link_to 'Back', articles_path %>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

    <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@article.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>

    <p>
      <%= f.submit %>
    </p>

<% end %>

app/views/articles/edit.html.erb
<%= render 'shared/navbar' %>

<h1>Edicion de Articulos</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<%= render 'shared/navbar' %>

<h1>Articulos de la lista</h1>

<hr>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>

  <% @article.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.text %></td>
        <td><%= link_to 'Show', article_path(article) %></td>
        <% if user_signed_in? %>
          <td><%= link_to 'Edit', edit_article_path(article) %></td>
          <td><%= link_to 'Destroy', article_path(article),
                          method: :delete,
                          data: { confirm: 'Are you sure?'} %></td>
        <% end %>
      </tr>
  <% end %>

</table>

app/views/articles/new.html.erb
<%= render 'shared/navbar' %>

<h1>Articulo Nuevo</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<%= render 'shared/navbar' %>

<p>
  <strong>Titulo: </strong>
  <%= @article.title %>
</p>

<p>
  <strong>Texto: </strong>
  <%= @article.text %>
</p>

<% if user_signed_in? %>
<%= link_to 'Edit Article', edit_article_path(@article) %>
<% end %>

<h2>Comments</h2>
<%= render @article.comments.last(10) %>
<!--Displays the most recent 10 comments-->

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter: </strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment: </strong>
  <%= comment.body %>
</p>


<% if user_signed_in? %>
  <p>
    <%= link_to 'Destroy Comment', [comment.article, comment],
                method: :delete,
                data: {confirm: 'Are you sure?'} %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
    <p>
      <%= f.label :commenter %><br>
      <%= f.text_field :commenter %>
    </p>
    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/comments/index.html.erb
<%= render 'shared/navbar' %>

<h1>Todos los Comments</h1>

<%= render @comments %>

<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">HLT-Blog</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!--<li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>-->
        <!--<li><a href="#">Link</a></li>-->
        <li>
          <%= link_to 'Mi Blog', articles_path %>
        </li>
        <% if user_signed_in? %>
            <li><%= link_to 'Nuevo Articulo', new_article_path %></li>
            <li><%= link_to 'Todos los comments', admin_comments_path %></li>
        <% end %>
        <!--<li class="dropdown">-->
          <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>-->
          <!--<ul class="dropdown-menu">-->
            <!--<li><a href="#">Action</a></li>-->
            <!--<li><a href="#">Another action</a></li>-->
            <!--<li><a href="#">Something else here</a></li>-->
            <!--<li role="separator" class="divider"></li>-->
            <!--<li><a href="#">Separated link</a></li>-->
            <!--<li role="separator" class="divider"></li>-->
            <!--<li><a href="#">One more separated link</a></li>-->
          <!--</ul>-->
        <!--</li>-->
      </ul>
      <!--<form class="navbar-form navbar-left" role="search">-->
        <!--<div class="form-group">-->
          <!--<input type="text" class="form-control" placeholder="Search">-->
        <!--</div>-->
        <!--<button type="submit" class="btn btn-default">Submit</button>-->
      <!--</form>-->
      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if user_signed_in? %>
            <li>
              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
            </li>
        <% else %>
            <li>
              <%= link_to('Login', new_user_session_path)  %>
            </li>
        <% end %>
        </li>
        <!--<li class="dropdown">-->
          <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>-->
          <!--<ul class="dropdown-menu">-->
            <!--<li><a href="#">Action</a></li>-->
            <!--<li><a href="#">Another action</a></li>-->
            <!--<li><a href="#">Something else here</a></li>-->
            <!--<li role="separator" class="divider"></li>-->
            <!--<li><a href="#">Separated link</a></li>-->
          <!--</ul>-->
        <!--</li>-->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/welcome/index.html.erb
<%= render 'shared/navbar' %>

<h1>Hola, Railes</h1>